[project]
name = 'farm'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.reflex]
path = 'contracts/reflex.clar'
clarity_version = 4
epoch = 'latest'

[contracts.tyccci40]
path = 'contracts/tyccci40.clar'
clarity_version = 4
epoch = 'latest'

[contracts.activity]
path = 'contracts/activity.clar'
clarity_version = 4
epoch = 'latest'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
